# Generated by Django 2.0.7 on 2018-08-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
